---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is RTD Logging component written in Python."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "RTD Logging component"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.DemoComp2:mqttproxy:1":
          policyDescription: "Allows access to publish to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.DemoComp2.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: "pip install snap7 boto3 botocore"
      run: "python3 -u {artifacts:decompressedPath}/com.example.DemoComp2/main.py {configuration:/Message}"
