---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Python."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "World"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.PythonMqttHello:mqttproxy:1":
          policyDescription: "Allows access to publish to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.example.PythonHelloWorld.zip"
        Unarchive: ZIP
    Lifecycle:
      # Install: "python3 -m pip install --user -r {artifacts:decompressedPath}/python-mqtt-hello/requirements.txt"
      run: "python3 -u {artifacts:decompressedPath}/com.example.PythonHelloWorld/main.py {configuration:/Message}"
