---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is a component written in Python which sends TIA data to Timestream."
ComponentPublisher: "Ojasvi Kumar"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "Tia to Timestream data streaming demo"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - Uri: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/demoTiaToTimestream.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: "python3 -m pip install --user -r {artifacts:decompressedPath}/demoTiaToTimestream/requirements.txt"
      run: "python3 -u {artifacts:decompressedPath}/com.example.PythonHelloWorld/main.py {configuration:/Message}"
